import React, { useState, useEffect } from 'react';
import { ProgramLevel } from '../types';
import { HELPDESK_PHONE, HELPDESK_WHATSAPP } from '../data/aiouData';
import { Sparkles, Send, Copy, Check, Printer, RefreshCw, MessageCircle, BookOpen, AlertCircle, Phone } from 'lucide-react';

interface AiAssignmentSolverProps {
  initialLevel?: ProgramLevel;
  initialCode?: string;
}

export const AiAssignmentSolver: React.FC<AiAssignmentSolverProps> = ({
  initialLevel,
  initialCode
}) => {
  const [programLevel, setProgramLevel] = useState<ProgramLevel>(initialLevel || 'B.Ed');
  const [courseCode, setCourseCode] = useState<string>(initialCode || '8601');
  const [prompt, setPrompt] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(false);
  const [solution, setSolution] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);

  useEffect(() => {
    if (initialLevel) setProgramLevel(initialLevel);
    if (initialCode) setCourseCode(initialCode);
  }, [initialLevel, initialCode]);

  const presetQuestions = [
    {
      code: '8601',
      level: 'B.Ed' as ProgramLevel,
      title: 'Teaching Methods (Code 8601)',
      q: 'Explain the principles of effective teaching methods and how to design a lesson plan for secondary level.'
    },
    {
      code: '8611',
      level: 'B.Ed' as ProgramLevel,
      title: 'Gibbs Reflective Cycle (Code 8611)',
      q: 'What is reflective practice in teaching? Explain Gibbs Reflective Cycle with all 6 stages and a practical classroom example.'
    },
    {
      code: '247',
      level: 'Matric' as ProgramLevel,
      title: 'General Math Compound Interest (Code 247)',
      q: 'Solve step-by-step: Calculate compound interest on PKR 50,000 at 8% per annum for 3 years for AIOU Matric assignment.'
    },
    {
      code: '1423',
      level: 'BA / AD' as ProgramLevel,
      title: 'English Letter & Essay (Code 1423)',
      q: 'Write a formal letter to AIOU Regional Director for book status + explain difference between skimming and scanning.'
    },
    {
      code: '5401',
      level: 'BS (4-Year)' as ProgramLevel,
      title: 'Programming Logic (Code 5401)',
      q: 'Write a recursive function in C++ and Python to calculate the factorial of a number with detailed code comments.'
    }
  ];

  const handleSolve = async (overridePrompt?: string) => {
    const queryToUse = overridePrompt || prompt;
    if (!queryToUse.trim()) {
      setError('Please enter your assignment question or subject query.');
      return;
    }

    setLoading(true);
    setError(null);
    setSolution(null);

    try {
      const res = await fetch('/api/ai/solve', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: queryToUse,
          courseCode,
          programLevel,
          mode: 'Assignment Solution & Tutor Help'
        }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || 'Failed to generate solution.');
      }

      setSolution(data.answer);
    } catch (err: any) {
      setError(err.message || 'Error communicating with AI Study Assistant.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!solution) return;
    navigator.clipboard.writeText(solution);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <html>
        <head>
          <title>AIOU Solved Assignment - Code ${courseCode}</title>
          <style>
            body { font-family: sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; }
            h1 { color: #065f46; border-bottom: 2px solid #065f46; padding-bottom: 10px; }
            .header-info { margin-bottom: 20px; font-weight: bold; background: #f0fdf4; padding: 15px; border-radius: 8px; }
            .content { white-space: pre-wrap; }
            .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; pt: 15px; text-align: center; font-size: 12px; color: #64748b; }
          </style>
        </head>
        <body>
          <h1>Educare Help Desk (03451291610) - AIOU Solution</h1>
          <div class="header-info">
            Program Level: ${programLevel} | Course Code: ${courseCode}<br/>
            Academic Session: 2025-2026 | Helpline: ${HELPDESK_PHONE}
          </div>
          <div class="content">${solution}</div>
          <div class="footer">
            Generated by Educare Help Desk AI Assistant for Allama Iqbal Open University Students.
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const whatsappShareUrl = solution
    ? `https://wa.me/${HELPDESK_WHATSAPP}?text=${encodeURIComponent(`Hello Educare Help Desk,\nI solved assignment Code ${courseCode} (${programLevel}) on your portal:\n\nQuestion: ${prompt.slice(0, 100)}...\n\nCan you verify if this is complete?`)}`
    : `https://wa.me/${HELPDESK_WHATSAPP}?text=${encodeURIComponent(`Hello Educare Help Desk, I need help solving assignment Code ${courseCode} (${programLevel}).`)}`;

  return (
    <div className="space-y-6 pb-12">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-emerald-900 to-slate-900 text-white rounded-2xl p-6 sm:p-8 shadow-md border border-emerald-700/60">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-2">
            <div className="inline-flex items-center gap-1.5 bg-amber-400 text-slate-950 font-extrabold text-[11px] uppercase tracking-wider px-2.5 py-0.5 rounded-full">
              <Sparkles className="w-3.5 h-3.5" />
              Gemini 3.6 Flash Powered
            </div>
            <h2 className="text-2xl sm:text-3xl font-bold font-serif text-amber-100">
              AIOU AI Assignment Solver & Study Assistant
            </h2>
            <p className="text-slate-300 text-xs sm:text-sm max-w-2xl">
              Paste your AIOU assignment questions or course queries (Matric, FA, BA, BS, B.Ed, MA, M.Phil, PhD) to generate structured academic solutions formatted for AIOU submission standards.
            </p>
          </div>

          <div className="bg-emerald-800/80 p-3.5 rounded-xl border border-emerald-600/50 text-xs text-amber-200 shrink-0">
            <div className="font-bold flex items-center gap-1">
              <Phone className="w-3.5 h-3.5 text-amber-400" />
              <span>Need Solved Assignments PDF?</span>
            </div>
            <div className="text-slate-200 mt-1">
              Contact Helpline: <a href={`tel:${HELPDESK_PHONE}`} className="underline font-bold text-white">{HELPDESK_PHONE}</a>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Input Controls Column */}
        <div className="lg:col-span-5 space-y-5">
          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-4">
            <h3 className="text-base font-bold text-slate-900 font-serif border-b border-slate-100 pb-2">
              Assignment & Course Parameters
            </h3>

            {/* Select Program Level */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                1. Select Program Level:
              </label>
              <select
                value={programLevel}
                onChange={(e) => setProgramLevel(e.target.value as ProgramLevel)}
                className="w-full bg-slate-50 border border-slate-300 text-slate-900 text-sm font-medium rounded-xl p-3 focus:ring-2 focus:ring-emerald-600 focus:outline-none"
              >
                <option value="Matric">Matric (SSC / 9th & 10th)</option>
                <option value="FA / Intermediate">FA / F.Sc / I.Com (11th & 12th)</option>
                <option value="BA / AD">BA / Associate Degree (AD)</option>
                <option value="BS (4-Year)">BS 4-Year Program</option>
                <option value="B.Ed">B.Ed (1.5 / 2.5 / 4 Year)</option>
                <option value="Master / PGD">Master Degree / PGD</option>
                <option value="M.Phil / MS">M.Phil / MS Program</option>
                <option value="Ph.D.">Ph.D. Program</option>
              </select>
            </div>

            {/* Course Code Input */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                2. AIOU Course Code (e.g., 8601, 247, 1423, 5401):
              </label>
              <input
                type="text"
                value={courseCode}
                onChange={(e) => setCourseCode(e.target.value)}
                placeholder="e.g. 8601"
                className="w-full bg-slate-50 border border-slate-300 text-slate-900 text-sm font-bold rounded-xl p-3 focus:ring-2 focus:ring-emerald-600 focus:outline-none"
              />
            </div>

            {/* Prompt Textarea */}
            <div>
              <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                3. Enter Question or Topic:
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                rows={5}
                placeholder="Paste question from your AIOU assignment book, e.g. 'Question 1: Explain lesson planning steps for secondary level students with examples...'"
                className="w-full bg-slate-50 border border-slate-300 text-slate-900 text-sm p-3 rounded-xl focus:ring-2 focus:ring-emerald-600 focus:outline-none leading-relaxed"
              />
            </div>

            {/* Submit Button */}
            <button
              onClick={() => handleSolve()}
              disabled={loading}
              className="w-full bg-emerald-800 hover:bg-emerald-900 text-white font-bold py-3.5 px-4 rounded-xl transition-all flex items-center justify-center gap-2 shadow-sm text-sm"
            >
              {loading ? (
                <>
                  <RefreshCw className="w-5 h-5 animate-spin text-amber-300" />
                  <span>Generating Detailed Solution...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-5 h-5 text-amber-300" />
                  <span>Solve Assignment Question</span>
                </>
              )}
            </button>

            {error && (
              <div className="bg-red-50 text-red-700 border border-red-200 p-3 rounded-xl text-xs flex items-start gap-2">
                <AlertCircle className="w-4 h-4 text-red-600 shrink-0 mt-0.5" />
                <span>{error}</span>
              </div>
            )}
          </div>

          {/* Quick Presets */}
          <div className="bg-emerald-50 p-5 rounded-2xl border border-emerald-200 space-y-3">
            <h4 className="text-xs font-extrabold uppercase text-emerald-900 tracking-wider flex items-center gap-1.5">
              <BookOpen className="w-4 h-4 text-emerald-700" />
              <span>Sample 1-Click Questions</span>
            </h4>
            <div className="space-y-2">
              {presetQuestions.map((pq, idx) => (
                <button
                  key={idx}
                  onClick={() => {
                    setProgramLevel(pq.level);
                    setCourseCode(pq.code);
                    setPrompt(pq.q);
                    handleSolve(pq.q);
                  }}
                  className="w-full text-left bg-white hover:bg-emerald-100/70 text-slate-800 p-2.5 rounded-xl border border-emerald-200 text-xs transition-colors space-y-0.5 group"
                >
                  <div className="font-bold text-emerald-900 group-hover:text-emerald-950 flex items-center justify-between">
                    <span>{pq.title}</span>
                    <span className="text-[10px] bg-emerald-100 text-emerald-800 px-1.5 py-0.2 rounded font-semibold">Try Now</span>
                  </div>
                  <p className="text-slate-600 line-clamp-1">{pq.q}</p>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Output Column */}
        <div className="lg:col-span-7">
          <div className="bg-white rounded-2xl border border-slate-200 shadow-xs min-h-[500px] flex flex-col justify-between overflow-hidden">
            {/* Output Header */}
            <div className="bg-slate-900 text-white px-6 py-4 flex flex-wrap items-center justify-between gap-3 border-b border-slate-800">
              <div>
                <span className="text-[10px] uppercase font-bold text-amber-400 tracking-wider block">
                  AIOU Solved Output
                </span>
                <h3 className="text-base font-bold font-serif text-white">
                  Course Code: <span className="text-amber-300">{courseCode || 'General'}</span> ({programLevel})
                </h3>
              </div>

              {solution && (
                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCopy}
                    className="bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold px-3 py-1.5 rounded-lg border border-slate-700 transition-colors flex items-center gap-1"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copied ? 'Copied!' : 'Copy'}</span>
                  </button>

                  <button
                    onClick={handlePrint}
                    className="bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold px-3 py-1.5 rounded-lg border border-slate-700 transition-colors flex items-center gap-1"
                  >
                    <Printer className="w-3.5 h-3.5 text-amber-400" />
                    <span>Print</span>
                  </button>
                </div>
              )}
            </div>

            {/* Output Body */}
            <div className="p-6 flex-1 overflow-y-auto max-h-[600px]">
              {loading ? (
                <div className="h-64 flex flex-col items-center justify-center space-y-3 text-slate-500">
                  <RefreshCw className="w-10 h-10 animate-spin text-emerald-600" />
                  <p className="text-sm font-semibold text-slate-700">Generating structured AIOU solution with Gemini 3.6 Flash...</p>
                  <p className="text-xs text-slate-500">Formulating headings, examples, and step-by-step points for Code {courseCode}</p>
                </div>
              ) : solution ? (
                <div className="prose prose-slate prose-sm max-w-none space-y-4">
                  <div className="bg-emerald-50 border-l-4 border-emerald-600 p-4 rounded-r-xl text-xs text-emerald-900 font-medium">
                    📌 <strong>AIOU Submission Format Tip:</strong> Format your handwritten or LMS typed assignment with bold headings and list points as generated below.
                  </div>

                  <div className="whitespace-pre-wrap font-sans text-slate-800 leading-relaxed text-sm">
                    {solution}
                  </div>
                </div>
              ) : (
                <div className="h-64 flex flex-col items-center justify-center text-center space-y-3 p-6 text-slate-400">
                  <div className="w-16 h-16 rounded-2xl bg-emerald-50 text-emerald-700 flex items-center justify-center">
                    <Sparkles className="w-8 h-8" />
                  </div>
                  <div>
                    <h4 className="text-base font-bold text-slate-700 font-serif">No Solution Generated Yet</h4>
                    <p className="text-xs text-slate-500 max-w-md mt-1">
                      Enter your question in the panel or click one of the sample 1-click questions to generate a detailed solution.
                    </p>
                  </div>
                </div>
              )}
            </div>

            {/* Output Footer */}
            <div className="bg-slate-50 p-4 border-t border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs">
              <div className="text-slate-600">
                Need original PDF file or tutor assistance?
              </div>

              <a
                href={whatsappShareUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="bg-emerald-700 hover:bg-emerald-800 text-white font-bold py-2 px-4 rounded-xl transition-all flex items-center gap-1.5 shadow-2xs"
              >
                <MessageCircle className="w-4 h-4 text-emerald-200" />
                <span>Ask Educare WhatsApp (03451291610)</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
